# Cloudflare Pages Configuration

name = "ridwansukri-portfolio"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

# Environment variables (jika diperlukan)
# [vars]
# PUBLIC_SITE_URL = "https://www.ridwansukri.com"
