export const siteConfig = {
	name: "Ridwan Sukri",
	title: "Ridwan Sukri - DevOps Engineer & Cloud Architect | AWS | Kubernetes",
	description:
		"DevOps Engineer specializing in AWS/Azure/GCP Cloud Infrastructure, Kubernetes Container Orchestration, CI/CD Pipelines, Infrastructure as Code (Terraform), and DevSecOps practices. Experienced in cloud automation, security best practices, and scalable system architecture.",
	url: "https://ridwansukri.com",
	ogImage: "https://ridwansukri.com/og-image.jpg",
	links: {
		github: "https://github.com/ridwansukri",
		linkedin: "https://linkedin.com/in/ridwansukri",
		email: "contact@ridwansukri.com",
		cv: "https://drive.google.com/file/d/YOUR_CV_FILE_ID/view",
	},
	author: {
		name: "Ridwan Sukri",
		title: "DevOps Engineer & Cloud Architect",
		bio: "Passionate DevOps Engineer with expertise in AWS/Azure/GCP Cloud platforms, Infrastructure as Code, Kubernetes orchestration, and DevSecOps practices. Specialized in building scalable, secure, and automated cloud infrastructure solutions.",
		location: "Indonesia",
		skills: {
			devops: [
				"Docker",
				"Kubernetes",
				"Terraform",
				"Jenkins",
				"GitHub Actions",
				"GitLab CI",
				"Ansible",
				"Helm",
				"Prometheus",
				"Grafana",
			],
			cloud: [
				"AWS",
				"Azure",
				"Google Cloud Platform",
				"AWS EC2",
				"AWS S3",
				"AWS Lambda",
				"AWS EKS",
				"Azure DevOps",
				"Google Kubernetes Engine",
				"CloudFormation",
				"ARM Templates",
			],
			programming: ["Python", "Bash", "Go", "JavaScript", "TypeScript", "YAML", "JSON"],
			security: [
				"DevSecOps",
				"Cloud Security",
				"OWASP",
				"Vulnerability Assessment",
				"IAM",
				"Zero Trust Architecture",
				"Security Automation",
				"Penetration Testing",
			],
			tools: [
				"Git",
				"Linux",
				"Nginx",
				"Apache",
				"MySQL",
				"PostgreSQL",
				"Redis",
				"ElasticSearch",
				"Vault",
				"Consul",
			],
		},
	},
	keywords: [
		"DevOps Engineer",
		"Cloud Architect",
		"AWS Certified",
		"Kubernetes",
		"Infrastructure as Code",
		"CI/CD Pipelines",
		"Container Orchestration",
		"DevSecOps",
		"Cloud Native",
		"Site Reliability Engineer",
		"Terraform",
		"Docker",
		"Cloud Security",
		"Multi-Cloud",
		"Indonesia",
	],
};
